package com.danilons.ecommerce;

import android.support.annotation.Nullable;

import java.io.Serializable;
import java.util.ArrayList;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/**
 * Created by danilons on 2017-04-11.
 */

public class User extends RealmObject {

    private String          name;
    private int             age;
    private String          password;
    private String          userName;
    private boolean         admin;
    private int userId;

    @Ignore
    private int             sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public int    getAge() { return age; }
    public void   setAge(int age) { this.age = age; }
    public String getUserName(){ return userName; }
    public  void setUserName(String userName){ this.userName = userName;}
    public String getPassword(){ return password;}
    public  void setPassword(String password){ this.password = password;}
    public int    getSessionId() { return sessionId; }
    public void   setSessionId(int sessionId) { this.sessionId = sessionId; }
    public boolean isAdmin() { return admin; }
    public void   setAdmin(boolean admin) { this.admin = admin; }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getUserId() {
        return userId;
    }
}